### ISSUE TITLE
Markers disappearing

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#198]
It is not uncommon for markers to disappear when using sea-app.

Try dotcoop.solidarityeconomy.coop
It is not reliably repeatable, but occurs often enough that it shouldn't take too long to replicate.

It has been observed on both Chrome and Firefox on Windows 10. The way to replicate is to use the Directory select countries and then to zoom to include all co-ops in that country by clicking the country name bar above the list of co-ops in the country. Moving between countries with several co-ops and then with only one or two like Belarus or Haiti frequently induces the error. Reselecting the co-op in the directory, or hiding the panel usually causes the marker to reappear.

**Comment by ColmMassey** [comment]
This has not been obsrved since the changes make to support hiding markers of initiatives that were not identified in a search, so happy to close.

**Comment by ColmMassey** [comment]
Actually I am still seeing this a lot. Zooming in and out induces it to return.

**Comment by ColmMassey** [comment]
This happening a lot on new ICA map.

**Comment by sunnydean** [comment]
This should be fixed alongside with the disappearing tiles fix (presumably)
Since I am failing to replicate it, could someone please test it out? @ColmMassey @wu-lee 
Thanks!
check out the new ica map: http://dev.ica.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
It would be useful to be able to test this on a bigger data set. Can you push the changes to dev.dotcoop.etc... ?

**Comment by sunnydean** [comment]
https://dev.dotcoop.solidarityeconomy.coop/
Sure 
@ColmMassey 

I don't see it happening but please double check

**Comment by ColmMassey** [comment]
I have observed it once, on Chrome. Seems less frequent, but not fully solved. I wonder is there any logging I can capture to share when I observe it.

**Comment by ColmMassey** [comment]
Also I think you may have made clustering at co-located addresses worse. Check out either Iran clusters on either Chrome or FIrefox.

**Comment by sunnydean** [comment]
I can further look into disappearing markers it if needed. could we have a really quick call to demo the bug on your screen because I cannot seem to replicate it at all?
(Make sure to use incognito to get the new code)

I  saw the issue with clustering though, will start fixing that next!

**Comment by ColmMassey** [comment]
I think you have solved the main cause of markers disappearing, (that is independent of the clustering issue). I have only observed it once in the last 1/2 hour of hammering it, so let's close this for now.

**Comment by sunnydean** [comment]
Note: 
We can reopen if it comes about again
I have a couple of other solutions if needed :)
